### ISSUE TITLE
Run Code Issue

### ISSUE THREAD

**Issue by smallcatd** [T3AS/MAD-ARL#2]
Hi,

I am facing some problems when I ran this code, the Carla window did not change and the specific situation of the vehicle could not be observed. When I checked the information, I found that the vehicle was constantly being created and destroyed.

How can I patch it and run the code properly.

Thanks!

**Comment by AizazSharif** [comment]
Hi @smallcatd 

Sorry for the delayed response. Could you please further describe the problem, maybe with screenshots as an example?
